name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:         # Allow manual runs from GitHub Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render backend
        run: |
          echo "Pinging backend at $(date)"
          curl -s https://kpugram-backend.onrender.com/actuator/health || echo "Ping failed"
